### ISSUE TITLE
RJ45 인터넷 속도

### ISSUE THREAD

**Issue by namyounsu** [deunlee/DeunDuino#1]
RJ45 연결 시 최대 예상 Speed Specs는 어떻게 되나요?

**Comment by deunlee** [comment]
DeunDuino NET에 사용된 WIZnet사의 W5500 이더넷 칩 스펙은 100BaseTX입니다.
실제 통신 속도는 SPI 클럭에 따라서 달라지는데 해당 부분은 테스트가 필요할 것 같습니다.

그리고 이 칩은 IoT용으로 설계되어서 고성능을 기대하기는 어려울 것 같습니다.
동시 소켓 수도 8개로 제한되어 퍼블릭 서버 등 용도로 사용하는 것 보다는, 내부 전용 서버나 IoT 클라이언트가 적합해 보입니다.

ESP32-S3는 이더넷 MAC이 내장되어 있지 않기 때문에 MII/RMII PHY를 사용할 수 없고 SPI를 사용해야 합니다.
추후 ARM이나 RISC-V 기반의 이더넷 MAC이 내장된 CPU 기반 보드를 만든다면 RGMII 등도 고려해 볼 예정입니다.
